### PR TITLE
Clean use_pkdown()

### PR DESCRIPTION
**Pull request by hsonne**
- improve indenting
- simplify names
- do not repeat KWB string -> new function kwb_string()
- use setNames()

---
This change is [Reviewable](https://reviewable.io/reviews/kwb-r/kwb.pkgbuild/33)

### CODE REVIEW

**Comment by mrustl** [comment]
@hsonne I am little  bit confused with the branch status but it seems that the dev branch is a little bit out of date

grafik

Are you sure that you have the latest changes from the master branch ?

**Comment by mrustl** [comment]
grafik

**Comment by hsonne** [comment]
We need to merge the master branch. Does that work here with a PR? I will try.

**Comment by mrustl** [comment]
Try it, I am totally lost......

**Comment by hsonne** [comment]
@mrustl Ok, dev should be up to date now. I protected the master branch. So that all commits should go into dev first and merged into master only with explicit PR.

**Comment by mrustl** [comment]
Ok, perfect. One conflict remaining ?

**Comment by mrustl** [comment]
@hsonne I just was able to commit directly to the master branch in https://github.com/KWB-R/kwb.pkgbuild/commit/a150398e21d977ac0d6f393f7ccfe335ad23e905

Just to inform you......

**Pull request merged**
