### PR TITLE
Clean code in helper.R

### PR DESCRIPTION
**Pull request by hsonne**
See my commit messages

---
This change is [Reviewable](https://reviewable.io/reviews/kwb-r/kwb.pkgbuild/31)

### CODE REVIEW

**Comment by mrustl** [comment]
Thanks for your effort. Please fix:

Error: Missing commas separating Remotes: 'github::kwb-r/kwb.utils
    github::ropenscilabs/

**Comment by mrustl** [comment]
___
*[DESCRIPTION, line 42 at r1](https://reviewable.io/reviews/kwb-r/kwb.pkgbuild/31#-LZVufV-9QdIzoiN6n7B:-LZVufV-9QdIzoiN6n7C:bdkd4ko) ([raw file](https://github.com/kwb-r/kwb.pkgbuild/blob/fd4bea5d0984bb61c0512afd462b08c6f45cbfd7/DESCRIPTION#L42)):*
> ```
>     testthat
> Remotes: 
>     github::kwb-r/kwb.utils
> ```

Please add the missing semicolon

**Comment by hsonne** [comment]
Done. Thanks for review!

**Comment by mrustl** [comment]
___
*[DESCRIPTION, line 42 at r1](https://reviewable.io/reviews/kwb-r/kwb.pkgbuild/31#-LZVufV-9QdIzoiN6n7B:-LZVyS2uDFMy4-ybJkW1:b-8fx2u7) ([raw file](https://github.com/kwb-r/kwb.pkgbuild/blob/fd4bea5d0984bb61c0512afd462b08c6f45cbfd7/DESCRIPTION#L42)):*
<details><summary><i>Previously, mrustl (Michael Rustler) wrote…</i></summary><blockquote>

Please add the missing semicolon 
</blockquote></details>

:+1:

**Comment by mrustl** [comment]
___
*[DESCRIPTION, line 42 at r1](https://reviewable.io/reviews/kwb-r/kwb.pkgbuild/31#-LZVufV-9QdIzoiN6n7B:-LZVyf_T0roXtbifsCIR:bebrt1w) ([raw file](https://github.com/kwb-r/kwb.pkgbuild/blob/fd4bea5d0984bb61c0512afd462b08c6f45cbfd7/DESCRIPTION#L42)):*
<details><summary><i>Previously, mrustl (Michael Rustler) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Will do

**Pull request merged**
